apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-alias
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/z-kim/ktcloud-sixsense-k3s.git
    targetRevision: test-argocd
    path: cluster/manifests/kafka-alias
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
