---
ansible_host: "{{ private_ip_address }}"
ansible_ssh_common_args: >-
  -o ProxyCommand="ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i {{ ansible_ssh_private_key_file }} -W %h:%p {{ ansible_user }}@{{ hostvars[groups['bastion'][0]].ansible_host }}"
  -o IdentitiesOnly=yes
  -o StrictHostKeyChecking=no
k3s_server_packages:
  - curl
  - tar
k3s_server_write_kubeconfig_mode: "644"
k3s_server_disable_components:
  - traefik
  - servicelb
k3s_server_node_labels:
  - node-role.k3s-project.io/control-plane=true
