apiVersion: v1
kind: ConfigMap
metadata:
  name: modsecurity-audit-sidecar-config
  namespace: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  fluent-bit.conf: |-
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/conf/parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_PORT 2020

    [INPUT]
        Name tail
        Path /var/log/audit/modsec_audit.log
        Tag modsecurity.audit
        Parser modsecurity_json
        DB /tmp/modsecurity-audit.db
        Read_from_Head On
        Refresh_Interval 5
        Rotate_Wait 5
        Skip_Long_Lines On

    [FILTER]
        Name grep
        Match modsecurity.audit
        Exclude $transaction['request']['headers']['User-Agent'] ^ELB-HealthChecker/2\.0$

    [OUTPUT]
        Name kafka
        Match modsecurity.audit
        Brokers kafka.logging.svc.cluster.local:9092
        Topics modsecurity-log
        Format json
        Timestamp_Key @timestamp
        Retry_Limit False
        rdkafka.client.id k3s_srv
  parsers.conf: |-
    [PARSER]
        Name modsecurity_json
        Format json
